apiVersion: v1
kind: Pod
metadata:
  name: spring-boot
  labels:
    app: spring-boot
spec:
  containers:
    - name: tomcat9
      image: tomcat:9
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
