apiVersion: v1
kind: ReplicationController
metadata:
  name: spring-boot
spec:
  replicas: 3
  selector:
    app: spring-boot
  template:
    metadata:
      name: spring-boot
      labels:
        app: spring-boot
    spec:
      containers:
        - name: tomcat9
          image: tomcat:9

