apiVersion: v1
kind: Pod
metadata:
  name: spring-boot
  labels:
    app: spring-boot
spec:
  containers:
    - name: tomcat9
      image: tomcat:9
      imagePullPolicy: IfNotPresent
      livenessProbe:
        httpGet:
          port: 8080
          path: /
        timeoutSeconds: 10
        initialDelaySeconds: 10
        periodSeconds: 30
  restartPolicy: Always
